model:
  layers:
    - type: Conv2D
      filters: 256
      kernel_size: [5, 5]
      activation: relu
      padding: same
      input_shape: [48, 48, 1]
    - type: MaxPooling2D
      pool_size: [2, 2]
      strides: [2, 2]
    - type: Dropout
      rate: 0.2
    - type: Conv2D
      filters: 128
      kernel_size: [5, 5]
      padding: same
      activation: relu
    - type: MaxPooling2D
      pool_size: [2, 2]
      strides: [2, 2]
    - type: Dropout
      rate: 0.3
    - type: Conv2D
      filters: 64
      kernel_size: [3, 3]
      padding: same
      activation: relu
    - type: MaxPooling2D
      pool_size: [2, 2]
      strides: [2, 2]
    - type: Dropout
      rate: 0.3
    - type: Conv2D
      filters: 32
      kernel_size: [3, 3]
      padding: same
      activation: relu
    - type: MaxPooling2D
      pool_size: [2, 2]
      strides: [2, 2]
    - type: Dropout
      rate: 0.3
    - type: Flatten
    - type: Dense
      units: 64
      activation: relu
    - type: Dropout
      rate: 0.3
    - type: Dense
      units: 32
      activation: relu
    - type: Dropout
      rate: 0.3
    - type: Dense
      units: 4
      activation: softmax
  compile:
    optimizer_name: nadam
    learning_rate: 0.0005
  train:
    epochs: 30
    batch_size: 16
    patience: 7
  data:
     color_mode: grayscale
     color_layers: 1
     img_width: 48
     img_height: 48
     use_data_loaders: true
# using https://dspace.library.uvic.ca/server/api/core/bitstreams/25d0a7d6-93af-4e58-a28d-a92dd8d45ca4/content